export const EDIT_REQUEST="EDIT_BOOK_REQUEST";
export const EDIT_SUCCESS="EDIT_BOOK_SUCCESS";
export const EDIT_FAILURE="EDIT_BOOK_FAILURE";

export const DELETE_REQUEST="EDIT_BOOK_REQUEST";
export const DELETE_SUCCESS="EDIT_BOOK_SUCCESS";
export const DELETE_FAILURE="EDIT_BOOK_FAILURE";